src/app/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^client/', include('client.urls', namespace='client')),
]

src/blog/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
  url(r'^index/$', views.index),
  url(r'^article/(?P<article_id>[0-9]+)/?$', views.article_page, name='article_page'),
  url(r'^edit/(?P<article_id>[0-9]+)/?$', views.edit_page, name='edit_page'),
  url(r'^edit/action/$', views.edit_action, name='edit_action'),
  url(r'^$', views.index),
]

src/client/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
  url(r'^index/', views.index),
  url(r'^$', views.index),
]

src/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Article(models.Model):
  # if u use python3, use `__str__(self)`
  # otherwise use `__unicode__(self)`
  title = models.CharField(max_length=32, default="title")
  content = models.TextField(null=True)
  pub_time = models.DateTimeField(auto_now=True)

  def __unicode__(self):
    return self.title

src/client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

src/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse
from . import models

# Create your views here.

def index(request):
  # query all
  articles = models.Article.objects.all()
  return render(request, 'blog/index.html', { 'articles': articles })

def article_page(request, article_id):
  # query only one
  article = models.Article.objects.get(pk=article_id)
  return render(request, 'blog/article.html', { 'article': article })

def edit_page(request, article_id):
  if str(article_id) == '0':
    return render(request, 'blog/edit.html')
  else:
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit.html', { 'article': article })

def edit_action(request):
  title = request.POST.get('title', 'TITLE')
  content = request.POST.get('content', 'CONTENT')
  models.Article.objects.create(title=title, content=content)

  article_id = request.POST.get('article_id', '0')

  if article_id == '0':
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', { 'articles': articles })
  else:
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article.html', { 'article': article })

src/client/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
  return render(request, 'client/index.html')

src/blog/templates/blog/article.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Details Blog {{title}}</title>
</head>
<body>
  <a href="{% url 'blog:edit_page' article.id %}">Edit</a>
  <h1>{{article.title}}</h1>
  <div class="p">{{article.content}}</div>
</body>
</html>

src/blog/templates/blog/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Edit Blog</title>
</head>
<body>
  <form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <!-- {% if article %} -->
    <!-- {% else %} -->
    <!-- {% endif %} -->
    <input type="hidden" name="article_d" value={{article.id | default:'0' }}>
    <div><label for="title" data-article="{{article}}">Title: <input required max-length="32" type="text" name="title" value="{{article.title}}"></label></div>
    <div><label for="content">Content: <textarea name="content" cols="30" rows="10">{{article.content}}</textarea></label></div>
    <div><input type="submit" value="submit"></div>
  </form>
</body>
</html>

src/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>All Blogs - Django HTML template</title>
</head>
<body>
<a href="{% url 'blog:edit_page' 0 %}">new article</a>
<h1>Articles:</h1>
<main>
  <ul>
    {% for article in articles %}
      <li>
        <!-- <a href="/blog/article/{{article.id}}/"><h3>{{ article.title }}</h3></a> -->
        <a href="{% url 'blog:article_page' article.id %}"><h3>{{ article.title }}</h3></a>
        <article>
          <p>{{article.content}}</p>
        </article>
      </li>
    {% endfor %}
  </ul>
</main>
</body>
</html>

src/client/templates/client/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django HTML template</title>
</head>
<body>
<h1>Hello World!</h1>
</body>
</html>